Update workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,13 +21,13 @@ jobs:
       - name: Run tests
         run: |
           # Run your script file here
-          sh -c "python src/main.py"
+          sh -c "python src/main.py";
           # Store the output of the script in a variable
-          fails=$?
+          fails=$?;
           # Check if the variable equals 0
           if [ $fails -eq 0 ]; then
-            echo "Tests passed"
-            exit 0
+            echo "Tests passed";
+            exit 0;
           else
-            echo "Tests failed"
-            exit 1
+            echo "Tests failed";
+            exit 1;
